### PR TITLE
New Post: Improving availability and performance with multi az architecture

### PR DESCRIPTION
**Pull request by cobusbernard**
# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

### CODE REVIEW

**Comment by cobusbernard** [comment]
New PR from old #250 , please continue working here. Due to making repo public.

**Comment by setheliot** [comment]
@cobusbernard @scribwell The review and iteration process has been ongoing in WorkDocs (see https://app.asana.com/0/1202460975106500/1204124169519733/f).  Next I have asked the author to get a review from a networking SME

**Review by setheliot — CHANGES_REQUESTED** [review]
1. Get review from Networking SME
2. Update content here with latest from WorkDocs
3. Get editorial review (from @damonk10 )

**Comment by cobusbernard** [comment]
Closing this PR, new one to use is #448.

**Pull request closed without merging**
