### PR TITLE
[New Post] Where Do I Put Stuff? Cloud Storage for the Busy Admin

### PR DESCRIPTION
**Pull request by spara**
# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ x] The title of this pull request reflects the title of my content.
- [ x] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ x] This pull request contains one piece of content (post or page).

### CODE REVIEW

**Review by cobusbernard — CHANGES_REQUESTED** [review]
@spara, looks like the folder was renamed with the last commit and there are now 2 versions of the post, could you take a look please and fix so there is only 1 folder? Thanks!

**Comment by spara** [comment]
> @spara, looks like the folder was renamed with the last commit and there are now 2 versions of the post, could you take a look please and fix so there is only 1 folder? Thanks!

If you're referring to this: where-do-i-put-my-backups-in-the-cloud, that's not my post, our title namespaces seem to have collided a bit.

Please hold off on the post, I'm working through a limitation with posting youtube videos with a specified start and end time. Cher is helping me out and I'll update the post when it gets resolved.

**Comment by bketelsen** [comment]
This PR still has two different articles included. Please remove the backups article from the PR to proceed. If you need assistance, please reach out I'll be glad to help.

**Review by spara — COMMENTED** [review]
removed extra post

**Comment by spara** [comment]
extra post removed

**Review by cherbk — APPROVED** [review]

**Comment by cobusbernard** [comment]
Closing the PR for now due to the post editor.

**Pull request closed without merging**
