### PR TITLE
[New post] Simonhanmer issue 764

### LINKED ISSUE #764: idea suggestion: Mystery of the disappearing S3 keys
### What is the title of the content you're proposing?
Mystery of the disappearing S3 keys

### Describe your content, including takeaways for the reader, in three to four sentences.
An overview of a recent incident we encountered, how we investigated and leading to a review of eventual consistency in S3. If accepted, there will be a second article reviewing the use of EventBridge, SQS and Lambda to handle events in a batch method including handling of partial batch failures.

### What theme is your content related to?
Storage

### When can you provide your first draft of content by?
September 30th

### What are 2-3 links to previous written content you have published?
https://headforthe.cloud/article/ssm-dhmc-intro/
https://headforthe.cloud/article/lost-in-translation/
https://headforthe.cloud/article/deploying-a-hugo-blog-with-codecatalyst/

### PR DESCRIPTION
**Pull request by simonhanmer**
# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

Resolves #764

### CODE REVIEW

**Comment by simonhanmer** [comment]
Hi - first contribution, so hopefully got everything in place.
Note that this is two posts as it's a series, wasn't sure whether to tick the one post/page box.

**Comment by cobusbernard** [comment]
> Hi - first contribution, so hopefully got everything in place. Note that this is two posts as it's a series, wasn't sure whether to tick the one post/page box.

All good, we generally prefer one post at a time, but with a series, this makes more sense. I made some small syntax fixes, and added the table of content to both pieces, going to publish now.

**Review by cobusbernard — APPROVED** [review]

**Comment by cobusbernard** [comment]
Thanks, great posts, love the spelunking to figure out these kinds of situations :)

**Comment by cobusbernard** [comment]
Also, if you wanted, you could use the `series.md` page to have an overview / detail of the series, similar to this EKS page: 
https://github.com/build-on-aws/content/blob/main/tutorials/navigating-amazon-eks/series.md

**Pull request merged**
