### PR TITLE
[New community post] re:Invent uncovered - Top tips for first-time attendees

### PR DESCRIPTION
**Pull request by cremich**
# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

### CODE REVIEW

**Comment by cremich** [comment]
The picture from Las Vegas in the header image was shot by myself during my last re:invent trip.

**Comment by cremich** [comment]
Saws in the preview, that the canonical URL to https://cremich.cloud/aws-reinvent-uncovered was not set. 
Did I set `externalCanonicalUrl` right in the front matter?

**Comment by cobusbernard** [comment]
> Saw in the preview, that the canonical URL to https://cremich.cloud/aws-reinvent-uncovered was not set. Did I set `externalCanonicalUrl` right in the front matter?

Heya @cremich , I took a look now and can see it:
```
<link rel="canonical" href="https://community.aws/posts/reinvent-uncovered"/>
```

 I replaced the table of content with an auto-generated one, you can take a look at my commit to see the change.

**Review by cobusbernard — APPROVED** [review]

**Comment by cobusbernard** [comment]
@cremich, just confirmed it is correct once published:

```
<link rel="canonical" href="https://cremich.cloud/aws-reinvent-uncovered"/>
```

**Comment by cobusbernard** [comment]
Thanks for the contribution, really appreciate it!

**Comment by cremich** [comment]
That is awesome. Thanks for your feedback and your review.
Was a great experience!

**Pull request merged**
