### PR TITLE
Sustainable Software Development Life Cycle (S-SDLC)

### PR DESCRIPTION
**Pull request by singhr2**
# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x ] The title of this pull request reflects the title of my content.
- [x ] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link. [N/A]

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](https://github.com/build-on-aws/content/blob/main/LICENSE). Notwithstanding the above, if you provide source code text within your content piece, you are providing such source code under the [MIT-0](https://opensource.org/license/mit-0/) license.**

### CODE REVIEW

**Comment by gaonkarr** [comment]
@singhr2 can we add an image or a architecture diagram or something to the blog?

**Comment by gaonkarr** [comment]
to mention multiple authors please do use following in the frontmatter:

authorGithubAlias: Author1
authorName: Author1first last
additionalAuthors: 
  - authorGithubAlias: Author2
    authorName: Author2first last
date: 2023-10-13
---

**Comment by gaonkarr** [comment]
also if you want it to generate a Table of content, (as blog is long) add following AFTER the frontmatter like shown below

```

date: YYYY-MM-DD
---

| ToC |
|-----|

```

**Comment by gaonkarr** [comment]
@singhr2 thanks for making the changes. You can also reduce the description text. Max 2 lines please.

**Comment by gaonkarr** [comment]
@cherbk author revisions done. please send for one-step review

**Comment by gaonkarr** [comment]
@singhr2 pinged on asana that he wants to fix some issues.

**Comment by singhr2** [comment]
@gaonkarr pushed the changes, Please do the needful to take it forward.

**Review by cobusbernard — APPROVED** [review]

**Pull request merged**
