### PR TITLE
New post: Sphinx documentation pipeline

### PR DESCRIPTION
**Pull request by jumic**
# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [X] The title of this pull request reflects the title of my content.
- [X] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [X] This pull request contains one piece of content (post or page).

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.
--> I proposed this post in the AWS Community Builders program.

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

### CODE REVIEW

**Comment by jumic** [comment]
The preview doesn't show the svg image. The [GitHub preview](https://github.com/jumic/content/blob/sphinx-documentation-pipeline/posts/how-to-automatically-release-sphinx-documentation-using-cdk-pipelines-and-a-custom-codebuild-image/index.md) shows it. Is this a problem in preview mode? Or are svg images not supported?

**Comment by cobusbernard** [comment]
Thanks @jumic, I shortened the folder name a bit to reduce the length, fixed up 1 broken image link, and some typos, publishing now :)

**Review by cobusbernard — APPROVED** [review]

**Comment by jumic** [comment]
@cobusbernard Thank you for your corrections and the approval. 👍

I hope it's fine to address these points here - please let me know if should open an issue or anything else. 

- The architecture diagram (svg image) is is missing on [community.aws](https://community.aws/posts/automatically-release-sphinx-documentation-cdk-pipelines-custom-codebuild-image). It works on [GitHub](https://github.com/build-on-aws/content/blob/main/posts/automatically-release-sphinx-documentation-cdk-pipelines-custom-codebuild-image/index.md). Is this a problem on community.aws?
- community.aws uses the GithHub profile pictures and adds an Amazon icon. I assume this should only be shown for AWS employees only, is this correct? My blog post shows the Amazon icon, but I'm not an AWS employee. How does the tool decide whether to show the icon or not?

**Comment by cobusbernard** [comment]
@jumic of course! And thanks for pointing this out, I just pushed a fix via #700 . I will need to dig into the svg issue more, it should work, you are the first to use an `.svg` here :)
For now, I've converted the image to a `.webp` so it renders while we take a look at what the issue is, and updated the employee icon to not show.

**Comment by cobusbernard** [comment]
@jumic thanks, appreciate it, I will step away and go drink my coffee first, shouldn't be operating a keyboard before then :)

**Pull request merged**
