### PR TITLE
Connect to an EC2 Mac instance

### PR DESCRIPTION
**Pull request by sebsto**
# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [X] The title of this pull request reflects the title of my content.
- [X] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [X] This pull request contains one piece of content (post or page).

Asana task : https://app.asana.com/0/1203842293073500/1204649720959213/f

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

### CODE REVIEW

**Comment by sebsto** [comment]
This branch / PR is a subbranch of [this PR](https://github.com/build-on-aws/content/pull/437)  as it links to files in the first tutorial of the series

**Comment by scribwell** [comment]
@bketelsen This article is ready for your technical review.

**Comment by bketelsen** [comment]
@sebsto this still has the extra article included. Please remove part one.

**Comment by sebsto** [comment]
@bkeslten this part 2 depends on part 1 as it links to it.  This branch is a sub-branch of the other one. I maintain the two together.

The suggestions you made on part 1 are in.
Waiting for your review on part 2.

part 3 and subsequent will be each on their own branch / PR as previous articles will already be published. This is a special case because we want to publish two articles in one shot

**Comment by bketelsen** [comment]
will need a rebase from #437 changes

**Review by cobusbernard — APPROVED** [review]

**Pull request merged**
